Merged PR 949523: appcenter build integration
- For _prod_ and _int_ builds (release and nightly) builds run Java unit tests on Android in App Center
- Adds optional upload of JUnit results to Azure Blob storage, default in CI build.
- To run locally (continue to) follow tests/appcenter/README.md

Related work items: #1617962

diff --git a/ci/build.yml b/ci/build.yml
--- a/ci/build.yml
+++ b/ci/build.yml
@@ -1051,6 +1051,119 @@ jobs:
       ArtifactName: Android
       publishLocation: Container
 
+- job: AndroidAppcenterTest
+  dependsOn: [Pre, AndroidBuild]
+  condition: and(succeeded(), contains(dependencies.Pre.outputs['var.SPEECHSDK_BUILD_PHASES'], ' AndroidAppcenterTest '))
+  pool:
+    name: Hosted VS2017
+  timeoutInMinutes: 30
+  variables:
+    SPEECHSDK_TEST_STORAGEACCOUNTNAME: csspeechtestdata
+    SPEECHSDK_TEST_CONTAINERNAME: testout-$(System.CollectionId)-$(System.DefinitionId)
+    SPEECHSDK_TEST_APPCENTERUPLOAD: https://$(SPEECHSDK_TEST_STORAGEACCOUNTNAME).blob.core.windows.net/$(SPEECHSDK_TEST_CONTAINERNAME)/$(Build.BuildId)/android-appcenter/
+    # We use versioned device sets in App Center so we can potentially extend
+    # them w/o breaking historical test.
+    APPCENTER_DEVICESET_VERSION: 1
+  steps:
+  - bash: ./ci/set-variables.sh
+    displayName: Set variables
+  - script: npm -g i appcenter-cli@1.1.13
+    displayName: Install AppCenter CLI
+  - task: DownloadBuildArtifacts@0
+    displayName: 'Downloading Android artifacts'
+    inputs:
+      artifactName: Android
+      downloadPath: $(System.ArtifactsDirectory)/In
+      itemPattern: |
+        **/Android-arm32/Release/**/com.microsoft.cognitiveservices.speech.*jar
+        **/Android-arm32/Release/**/libMicrosoft.CognitiveServices.Speech.*.so
+  - bash: |
+      . ci/functions.sh &&
+      vsts_setvar SPEECHSDK_SASTOKENEXPIRYUTC $(date -u -d "2 hours" +"%Y-%m-%dT%H:%M:%SZ")
+    displayName: 'Define expiry time for SAS token (2 hours ahead)'
+  - task: AzureCLI@1
+    displayName: Generate SAS token
+    inputs:
+      azureSubscription: 'Custom Speech Development (3a96ef56-41a9-40a0-b0f3-fb125c2b8798) - RG csspeechsdk-carbon'
+      scriptLocation: inlineScript
+      inlineScript: |
+        @echo off
+        setlocal enabledelayedexpansion
+        @REM create container if it does not exist
+        call az storage container create --name %SPEECHSDK_TEST_CONTAINERNAME% --account-name %SPEECHSDK_TEST_STORAGEACCOUNTNAME% || exit /b 1
+        @REM Generate SAS. Note: no echo
+        set TOKEN=
+        for /f %%i in ('call az storage container generate-sas --name %SPEECHSDK_TEST_CONTAINERNAME% --account-name %SPEECHSDK_TEST_STORAGEACCOUNTNAME% --https-only --expiry %SPEECHSDK_SASTOKENEXPIRYUTC% --permissions dlrw -o tsv') DO set "TOKEN=%%~i"
+        if not defined TOKEN echo Error acquiring token.&exit /b 1
+        echo ##vso[task.setvariable variable=SPEECHSDK_SASTOKEN;issecret=true]!TOKEN!
+        set TOKEN=
+  - bash: |
+      set -u -x -e -o pipefail
+      FAKE_BUILD=buildfromrelease
+      mkdir -p "$FAKE_BUILD"{/bin,/lib}
+      DROP_DIR=$(cygpath -au "$(System.ArtifactsDirectory)/In/Android/Android-arm32/Release")
+      eval $(perl ci/evaluate-test-config.pl --verbose --format bash-variable --input ci/test-config.json \
+        -D luis-key=$(luis-westus-s0-201809-key1) \
+        -D speech-key=$(NorthEuropeKeySkyman) \
+        -D long-running=false)
+      cat > "$FAKE_BUILD/MainActivity.properties" <<EOF
+      SpeechSubscriptionKey=$SPEECHSDK_SPEECH_KEY
+      SpeechRegion=$SPEECHSDK_SPEECH_REGION
+      LuisSubscriptionKey=$SPEECHSDK_LUIS_KEY
+      LuisRegion=$SPEECHSDK_LUIS_REGION
+      LuisAppId=$SPEECHSDK_LUIS_HOMEAUTOMATION_APPID
+      Keyword=Computer
+      KeywordModel=kws-computer.zip
+      SasToken=$(SPEECHSDK_SASTOKEN)
+      SasContainerPrefix=$(SPEECHSDK_TEST_APPCENTERUPLOAD)
+      EOF
+      cat "$FAKE_BUILD/MainActivity.properties"
+      cp --preserve "$DROP_DIR/public/lib/com.microsoft.cognitiveservices.speech.jar" "$FAKE_BUILD/lib"
+      cp --preserve "$DROP_DIR/private/bin/com.microsoft.cognitiveservices.speech.tests.jar" "$FAKE_BUILD/bin"
+      cp --preserve "$DROP_DIR/public/lib/libMicrosoft.CognitiveServices.Speech.core.so" "$FAKE_BUILD/lib"
+      cp --preserve "$DROP_DIR/public/lib/libMicrosoft.CognitiveServices.Speech.java.bindings.so" "$FAKE_BUILD/bin"
+      find "$FAKE_BUILD" -ls
+    displayName: 'Prepare (fake) build dir for kicking off AppCenter tests'
+  - script: |
+      set APPCENTER_USER_ID=Speech-SDK-Test
+      set APPCENTER_TOKEN_OPTION=--token $(AppCenterToken)
+      @REM TODO allow to override when scheduling builds:
+      set APPCENTER_DEVICESET=deviceset-$(SPEECHSDK_BUILD_TYPE):$(APPCENTER_DEVICESET_VERSION)
+      call .\tests\appcenter\java-android\run_tests.bat buildfromrelease
+      @REM Error level will be reported later.
+      echo ##vso[task.setvariable variable=TEST_ERRORLEVEL]%ERRORLEVEL%
+      exit /b 0
+    displayName: Run tests in App Center
+  - script: |
+      @REM Note: Ignoring errors
+      setlocal enabledelayedexpansion
+      "C:\Program Files (x86)\Microsoft SDKs\Azure\AzCopy\AzCopy.exe" ^
+        /Source:%SPEECHSDK_TEST_APPCENTERUPLOAD% ^
+        /Dest:appcentertestresults ^
+        /SourceSAS:"?!sastoken!" ^
+        /S /Y /MT /XO
+      dir /s/a/b appcentertestresults
+      exit /b 0
+    displayName: Download test results from Azure Blob Storage
+    env:
+      sastoken: $(SPEECHSDK_SASTOKEN)
+  # TODO would be nice to know how many logs to expect. But it seems would have to parse appcenter cli output for this.
+  - task: PublishTestResults@2
+    inputs:
+      testResultsFiles: appcentertestresults/**.xml
+    condition: eq(variables['SPEECHSDK_RUN_TESTS'], 'true')
+    displayName: Publish test results
+  # Note: blob storage cleanup is implemented by a separate task (to be implemented).
+  - script: |
+      @echo off
+      if %TEST_ERRORLEVEL% gtr 0 (
+        echo AppCenter test run failed earlier, will return an error.
+        echo For further details, inspect the task log of the earlier ^"Run tests in App Center^" step,
+        echo the test results page of the build in Azure DevOps, or the test run page in App Center.
+      )
+      exit /b %TEST_ERRORLEVEL%
+    displayName: Return test error
+
 - job: AndroidPackage
   dependsOn: [Pre, AndroidBuild]
   condition: and(succeeded(), contains(dependencies.Pre.outputs['var.SPEECHSDK_BUILD_PHASES'], ' AndroidPackage '))
