Merged PR 1613910: nuget osx test retry logic changes
The current nuget osx takes huge amount of time because of retries. It generally takes more than 4 hours and sometime it gets out of time. changing the logic here for the retry

Related work items: #2689153

diff --git a/ci/build-jobs.yml b/ci/build-jobs.yml
--- a/ci/build-jobs.yml
+++ b/ci/build-jobs.yml
@@ -1007,21 +1007,50 @@ jobs:
 
       # set +e to allow captureing exit codes and retry loop, rather than blindly exiting the bash shell on error.
       set +e
-      for retry in {0..3}; do
-        dotnet test --blame --verbosity detailed --filter \
-          "TestCategory!=LongTest&TestCategory!=SpeechSynthesisMockTest&ClassName!=Microsoft.CognitiveServices.Speech.Tests.EndToEnd.KwsRecognitionTests&ClassName!=Microsoft.CognitiveServices.Speech.Tests.EndToEnd.KwsRecognizerTests&TestCategory!=CompressedStreamTest&TestCategory!=OfflineUnidec" \
-          --framework netcoreapp2.0 --settings csharp.runsettings --logger "trx;LogFileName=test-csharp_osx_unit_tests_$retry.trx"
-        exitCode=$?
-        if [[ $exitCode == 0 ]]; then
-          echo "Test suite passed, RetryCount( $retry )"
-          break
+
+      ACTUAL_LOG_FILE_NAME=test-csharp_osx_unit_tests
+      LOG_FILE_NAME=LogFileName=$ACTUAL_LOG_FILE_NAME.trx
+      echo $ACTUAL_LOG_FILE_NAME
+      echo $LOG_FILE_NAME
+      dotnet test --blame --verbosity detailed --filter \
+      "TestCategory!=LongTest&TestCategory!=SpeechSynthesisMockTest&ClassName!=Microsoft.CognitiveServices.Speech.Tests.EndToEnd.KwsRecognitionTests&ClassName!=Microsoft.CognitiveServices.Speech.Tests.EndToEnd.KwsRecognizerTests&TestCategory!=CompressedStreamTest&TestCategory!=OfflineUnidec" \
+      --framework netcoreapp2.0 --settings csharp.runsettings --logger "trx;$LOG_FILE_NAME"
+
+      exitCode=$?
+
+      ACTUAL_LOG_FILE_NAME_RETRY=$ACTUAL_LOG_FILE_NAME
+
+      for i in $(seq 1 4); do
+        if [[ $exitCode != 0 ]]; then
+          echo Parsing the trx file "./TestResults/$ACTUAL_LOG_FILE_NAME_RETRY.trx"
+          tests=""
+          FAILED="outcome=\"Failed\""
+          TESTNAME="testName"
+          while read p; do
+            if [[ "$p" == *"$FAILED"* ]] && [[ "$p" != *parentExecutionId* ]]; then
+              words=( $p )
+              for q in "${words[@]}"; do
+                if [[ "$q" == *"$TESTNAME"* ]] ; then
+                  test=${q:10}
+                  test="${test::-1}"
+                  tests="$tests | (Name=$test)"
+                fi
+              done
+            fi
+          done <"./TestResults/$ACTUAL_LOG_FILE_NAME_RETRY.trx"
+          tests=${tests:3}
+
+          ACTUAL_LOG_FILE_NAME_RETRY=$ACTUAL_LOG_FILE_NAME-retry$i
+          LOG_FILE_NAME_RETRY=LogFileName=$ACTUAL_LOG_FILE_NAME_RETRY.trx
+
+          echo "Rerunning the following failed test "
+          echo "${tests[*]}"
+          dotnet test --blame --verbosity detailed --filter "$tests" --framework netcoreapp2.0 --settings csharp.runsettings --logger "trx;$LOG_FILE_NAME_RETRY"
+          exitCode=$?
         else
-          echo "Test suite failed during retry( $retry )."
-          vsts_logissue warning "Test suite failed during retry( $retry )."
-          sleep 2s
+          break
         fi
       done
-      set -e
       exit ${exitCode}
     displayName: Run C# unit tests
     condition: eq(variables['SPEECHSDK_RUN_TESTS'], 'true')
